global:
  scrape_interval: 15s # 15초마다 메트릭 수집
  evaluation_interval: 15s # alert rule 평가 간격

scrape_configs:
  - job_name: 'musicplace-backend'
    metrics_path: '/actuator/prometheus' # 스프링 부트 지표 경로
    static_configs:
      - targets: ['host.docker.internal:8081'] # Spring Boot 애플리케이션 주소
